[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle client-side routing for Next.js
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://taskforge-5wdo.onrender.com"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
  NEXT_PUBLIC_API_URL = "https://taskforge-5wdo.onrender.com"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_API_URL = "https://taskforge-5wdo.onrender.com"
